In [2]:
a= 10 # Assign 10 to variable a
b= 20 # Assign 20 to variable b

In [3]:
a+b# Assign 20 to variable b

30

#  python basics

In [4]:
def greet():# Define a function named greet
   print ("hello world!")# Inside the function, print "hello world!"
greet()# Call the function greet to execute the print statement

hello world!

Salary prediction using employee years of experience

In [5]:
 !pip install pandas# Install pandas library (only works in Jupyter or notebook environment)

Requirement already satisfied: pandas in c:\users\indhumathi\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\indhumathi\appdata\roaming\python\python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\indhumathi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\indhumathi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\indhumathi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\indhumathi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
 import pandas as pd# Import the pandas library and give it the alias 'pd'

In [7]:
Dataset = pd.read_csv("Salary_Data.csv")# Read the CSV file named "Salary_Data.csv" into a pandas DataFrame called Dataset

In [8]:
Dataset# Display the contents of the Dataset

     YearsExperience  Salary
0                1.1   39343
1                1.3   46205
2                1.5   37731
3                2.0   43525
4                2.2   39891
..               ...     ...
184             10.3  122391
185             10.5  121872
186             11.0   12000
187             12.0   13500
188             13.0   14000

[189 rows x 2 columns]

In [9]:
independent = Dataset [['YearsExperience']]# Select the 'YearsExperience' column from Dataset as the independent variable (X)

In [10]:
dependent = Dataset [['Salary']]# Select the 'Salary' column from Dataset as the dependent variable (y)

In [11]:
from sklearn.model_selection import train_test_split# Import the train_test_split function from scikit-learn

In [17]:
train_test_split(independent,dependent,test_size =0.30,random_state=0)# Split the data into training and testing sets
# test_size=0.30 means 30% of the data will be for testing, 70% for training
# random_state=0 ensures the split is reproducible

[     YearsExperience
 16               5.1
 51               7.1
 86               9.5
 130              3.2
 40               3.9
 ..               ...
 103              3.9
 67               3.2
 117              8.7
 47               5.3
 172              6.0

 [132 rows x 1 columns],
      YearsExperience
 108              4.9
 74               4.5
 161              3.2
 95               1.5
 123              1.1
 71               4.0
 18               5.9
 124              1.3
 143              6.8
 7                3.2
 5                2.9
 186             11.0
 156              2.0
 168              4.9
 184             10.3
 113              6.8
 37               3.2
 66               3.0
 136              4.1
 131              3.2
 56               9.5
 101              3.2
 134              4.0
 179              9.5
 170              5.3
 150              9.6
 63               2.0
 60               1.1
 116              8.2
 33               2.0
 4                2.2
 55               9.0
 94               1.3
 44               4.5
 45               4.9
 26               9.5
 175              7.9
 138              4.9
 111              5.9
 8                3.2
 106              4.1
 89              10.5
 90               9.6
 171              5.9
 173              6.8
 109              5.1
 24               8.7
 30               1.1
 141              5.9
 61               1.3
 174              7.1
 137              4.5
 19               6.0
 144              7.1
 83               8.2
 54               8.7
 154              1.3,
      Salary
 16    66029
 51    98273
 86   116969
 130   54445
 40    63218
 ..      ...
 103   63218
 67    54445
 117  109431
 47    83088
 172   93940

 [132 rows x 1 columns],
      Salary
 108   67938
 74    61111
 161   64445
 95    37731
 123   39343
 71    55794
 18    81363
 124   46205
 143   91738
 7     54445
 5     56642
 186   12000
 156   43525
 168   67938
 184  122391
 113   91738
 37    54445
 66    60150
 136   57081
 131   64445
 56   116969
 101   64445
 134   55794
 179  116969
 170   83088
 150  112635
 63    43525
 60    39343
 116  113812
 33    43525
 4     39891
 55   105582
 94    46205
 44    61111
 45    67938
 26   116969
 175  101302
 138   67938
 111   81363
 8     64445
 106   57081
 89   121872
 90   112635
 171   81363
 173   91738
 109   66029
 24   109431
 30    39343
 141   81363
 61    46205
 174   98273
 137   61111
 19    93940
 144   98273
 83   113812
 54   109431
 154   46205]

In [12]:
X_train,X_test,y_train,y_test = train_test_split(independent,dependent,test_size =0.30,random_state=0)# Split data into train and test sets (70% train, 30% test)

In [13]:
X_train# Show training features

     YearsExperience
16               5.1
51               7.1
86               9.5
130              3.2
40               3.9
..               ...
103              3.9
67               3.2
117              8.7
47               5.3
172              6.0

[132 rows x 1 columns]

In [14]:
X_test#show test features

     YearsExperience
108              4.9
74               4.5
161              3.2
95               1.5
123              1.1
71               4.0
18               5.9
124              1.3
143              6.8
7                3.2
5                2.9
186             11.0
156              2.0
168              4.9
184             10.3
113              6.8
37               3.2
66               3.0
136              4.1
131              3.2
56               9.5
101              3.2
134              4.0
179              9.5
170              5.3
150              9.6
63               2.0
60               1.1
116              8.2
33               2.0
4                2.2
55               9.0
94               1.3
44               4.5
45               4.9
26               9.5
175              7.9
138              4.9
111              5.9
8                3.2
106              4.1
89              10.5
90               9.6
171              5.9
173              6.8
109              5.1
24               8.7
30               1.1
141              5.9
61               1.3
174              7.1
137              4.5
19               6.0
144              7.1
83               8.2
54               8.7
154              1.3

In [17]:
y_train.shape# Show training features

(132, 1)

In [19]:
y_test#show test features

     Salary
108   67938
74    61111
161   64445
95    37731
123   39343
71    55794
18    81363
124   46205
143   91738
7     54445
5     56642
186   12000
156   43525
168   67938
184  122391
113   91738
37    54445
66    60150
136   57081
131   64445
56   116969
101   64445
134   55794
179  116969
170   83088
150  112635
63    43525
60    39343
116  113812
33    43525
4     39891
55   105582
94    46205
44    61111
45    67938
26   116969
175  101302
138   67938
111   81363
8     64445
106   57081
89   121872
90   112635
171   81363
173   91738
109   66029
24   109431
30    39343
141   81363
61    46205
174   98273
137   61111
19    93940
144   98273
83   113812
54   109431
154   46205

In [22]:
y_train.shape# 132 rows (samples) and 1 column (target value)

(132, 1)

In [23]:
y_test.shape# 57 samples and 1 output value

(57, 1)

In [24]:
X_train.shape# 132 samples with 1 feature

(132, 1)

In [25]:
X_test.shape# 57 samples with 1 feature

(57, 1)

In [26]:
from sklearn.linear_model import LinearRegression# Import Linear Regression model from sklearn

In [30]:
regressor=LinearRegression()# Create (initialize) the Linear Regression model

In [33]:
regressor.fit(X_train,y_train)# Train the model using training input (X_train)
# and training output (y_train)

LinearRegression()

In [35]:
weight = regressor.coef_# Get model weight (slope)

In [36]:
weight

array([[7999.22258339]])

In [39]:
bias = regressor.intercept_# Get model bias (intercept)

In [40]:
bias

array([31716.67857177])

In [42]:
y_predict=regressor.predict(X_test)# Predict output for test data

In [46]:
from sklearn.metrics import r2_score# Calculate model accuracy (R² score)

In [47]:
r_score =r2_score(y_test,y_predict)

In [48]:
import pickle# Save the trained model

In [49]:
filename ="final_model_slr.pkl"# File name to save the trained model

In [50]:
pickle.dump(regressor,open(filename,'wb'))
pickle.dump(regressor,open(filename,'wb')

In [56]:
loaded_model =pickle.load(open("final_model_slr.pkl",'rb'))

In [59]:
loaded_model.predict([[54]])

C:\Users\INDHUMATHI\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[463674.69807487]])